spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 8000



### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
xxl:
  job:
    admin:
      addresses: http://localhost:8089/xxl-job-admin
    executor:
      appname: boot-job
      ip:
      port: 8000
      logpath:
      logretentiondays: -1
    accessToken:

###执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#xxl.job.executor.appname=xxl-job-executor-sample
#执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#xxl.job.executor.ip=192.168.112.227
#xxl.job.executor.port=9999
#xxl.job.login.username=admin
#xxl.job.login.password=123456

#xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
#执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
#xxl.job.executor.logretentiondays=-1
### 执行器通讯TOKEN [选填]：非空时启用；
#xxl.job.accessToken=