spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
minio:
  endpoint: http://192.168.0.104:9000
  accessKey: admin
  secretKey: admin
  bucketName: defaultBucket